### ISSUE TITLE
Error when launching and downloading files.

### ISSUE THREAD

**Issue by SteamHydra** [WynnMods/WynnMods.github.io#2]
Here are the steps I did when I downloaded the Launcher:
>Double click WC launcher jar
>Pressed Launch
>Input Mc login details
>Tells me to check which mods to download (checked all the recommended ones)
>Error popup

**To report this error, please provide:**

java.io.IOException: 79 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:172)
	at com.skcraft.launcher.update.Updater.call(Updater.java:89)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by DRedDogPE** [comment]
Restart the launcher and download the files again.
